import { type UnitShare } from './columns';

export async function getUnitShares(): Promise<UnitShare[]> {
  return [
    {
      id: 'unit-a-101',
      unit: 'A-101',
      type: 'apartment',
      coOwner: 'Ahmed Benali',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'syndic',
    },
    {
      id: 'unit-a-201',
      unit: 'A-201',
      type: 'apartment',
      coOwner: 'Karim Alaoui',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-202',
      unit: 'A-202',
      type: 'apartment',
      coOwner: 'Nadia Cherkaoui',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-301',
      unit: 'A-301',
      type: 'apartment',
      coOwner: 'Hassan Tazi',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-302',
      unit: 'A-302',
      type: 'apartment',
      coOwner: 'Laila Mansouri',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-401',
      unit: 'A-401',
      type: 'apartment',
      coOwner: 'Youssef Idrissi',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-402',
      unit: 'A-402',
      type: 'apartment',
      coOwner: 'Sara El Fassi',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-501',
      unit: 'A-501',
      type: 'apartment',
      coOwner: 'Mohamed Berrada',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-com-01',
      unit: 'COM-01',
      type: 'commercial',
      coOwner: 'SARL Atlas Commerce',
      coefficient: 1.5,
      quotaYear: 9000,
      quotaMonth: 750,
      status: 'co-owner',
    },
    {
      id: 'unit-stk-01',
      unit: 'STK-01',
      type: 'storage',
      coOwner: 'Rachid Ouali',
      coefficient: 0.5,
      quotaYear: 3000,
      quotaMonth: 250,
      status: 'co-owner',
    },

    // Additional rows for testing pagination
    {
      id: 'unit-a-502',
      unit: 'A-502',
      type: 'apartment',
      coOwner: 'Imane Zahraoui',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-601',
      unit: 'A-601',
      type: 'apartment',
      coOwner: 'Omar El Amrani',
      coefficient: 1.2,
      quotaYear: 7200,
      quotaMonth: 600,
      status: 'co-owner',
    },
    {
      id: 'unit-a-602',
      unit: 'A-602',
      type: 'apartment',
      coOwner: 'Salma Bennani',
      coefficient: 0.8,
      quotaYear: 4800,
      quotaMonth: 400,
      status: 'co-owner',
    },
    {
      id: 'unit-a-701',
      unit: 'A-701',
      type: 'apartment',
      coOwner: 'Anas Chraibi',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-com-02',
      unit: 'COM-02',
      type: 'commercial',
      coOwner: 'SARL Casablanca Services',
      coefficient: 2,
      quotaYear: 12000,
      quotaMonth: 1000,
      status: 'co-owner',
    },
    {
      id: 'unit-stk-02',
      unit: 'STK-02',
      type: 'storage',
      coOwner: 'Karim Naciri',
      coefficient: 0.5,
      quotaYear: 3000,
      quotaMonth: 250,
      status: 'co-owner',
    },
    {
      id: 'unit-a-702',
      unit: 'A-702',
      type: 'apartment',
      coOwner: 'Meryem Alaoui',
      coefficient: 1,
      quotaYear: 6000,
      quotaMonth: 500,
      status: 'co-owner',
    },
    {
      id: 'unit-a-801',
      unit: 'A-801',
      type: 'apartment',
      coOwner: 'Ayoub Tahiri',
      coefficient: 1.3,
      quotaYear: 7800,
      quotaMonth: 650,
      status: 'co-owner',
    },
  ];
}
